[project]
name = "gorragor-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "selenium>=4.18.1",
    "webdriver-manager>=4.0.1",
    "sqlalchemy>=2.0.25",
    "psycopg2-binary>=2.9.9",
    "pyspark>=4.1.1",
    "polars>=1.0.0",
    "rapidfuzz>=3.0.0",
    "kaggle>=2.2.0",
]
